### ISSUE TITLE
nextselfhost.dev Doesn't seem to work properly. Screenshot inside

### ISSUE THREAD

**Issue by amiranvarov** [leerob/next-self-host#2]
Hey, 

I just opened https://nextselfhost.dev/, and it doesn't seem to work properly. Here is the screenshot:

<img width="1814" alt="image" src="https://github.com/user-attachments/assets/2b6b67be-b5fc-49fd-a616-73302bf42a4f">

Thanks for your work

**Comment by leerob** [comment]
That is correct 😄 There are no styles. Am I missing something else?

**Comment by leerob** [comment]
Added some styles
