### ISSUE TITLE
Migrations are not run on deployment/prod

### ISSUE THREAD

**Issue by lgraubner** [leerob/next-self-host#4]
I noticed you added a migration script at `app/db/migrate.ts` but it's not referenced anywhere. This works fine when calling for local development, but it's not added to the production build as far as I can see.

I struggled with this in the past and could only come up with non ideal solutions (such as bundling and copying the script separately etc.). Do you have any recommendation how to handle this in a better way?

Appreciate your efforts so far. :)

**Comment by wlgs** [comment]
I would also love to receive any idea how to handle this. My main problem is that you can't really run migration scripts in docker env (such as drizzle-kit migrate) during build time because the db would not be available at that time. To run them right after db started, you would need something like this in your dockerfile:

`CMD ["/bin/sh", "-c", "pnpm db:migrate && pnpm start || exit 1"]`

But then you can't use the standalone output mode.

I've also tried to create custom dockerfile for db which would copy migration files that drizzle generates and directly connect to db console and run them but I'm not convinced it's the right way.

Great repo, I've learned a lot ❤️

**Comment by garnerp** [comment]
We have a few versions of this running. One is to create a docker layer to get the node modules only needed to run the migrate, then copy that into the final docker container (right where we copy in the standalone directories).  Seems to be working ok.

**Comment by bikram20** [comment]
An option is to keep migrations in a different container and run it before web service starts. 

**Dockerfile.migrations:**
FROM oven/bun:alpine

WORKDIR /app

# Copy package.json and lockfile
COPY package.json bun.lockb ./

# Install dependencies
RUN bun install --frozen-lockfile

# Copy application code
COPY . .

# Set environment variables
ENV NODE_ENV=production

# Run migrations
CMD ["bun", "run", "app/db/migrate.ts"]



**Revised docker-compose.yml:**
root@next-selfhost-demo:~/next-self-host# cat docker-compose.yml 
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - migration
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - my_network

  cron:
    image: alpine/curl
    command: >
      sh -c "
        echo '*/10 *  * * *  curl -X POST http://web:3000/db/clear' > /etc/crontabs/root && \
        crond -f -l 2
      "
    depends_on:
      - web
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    name: my_network
    driver: bridge
root@next-selfhost-demo:~/next-self-host# 


This ensures migration container runs every time before web service. You can exec into it anytime:
docker-compose run --rm migration /bin/sh

**Comment by lgraubner** [comment]
I like your solution, thanks :)
